#CC madlibs. Again
print("This is an automated madlib lib game")
noun_1= input("Give me a noun: ")
plural_noun=input("Give me a plural noun: ")
verbing=input("Give me an ing verb: ")
city=input("Give me a city: ")
plural_noun_2=input("Give me another plural noun: ")
adjective1=input("Give me an adjective: ")
num=input("give me a number: ")
noun2=input("Give me another noun: ")
adjective2=input("Give me another adjective: ")
verb=input("Give me a verb: ")
verb2=input("Give me another verb: ")
adverb=input("Give me an adverb: ")
noun3=input("Give me another noun bro: ")
adjective3=input("Give me another adjective: ")
verbing2=input("give me an ing verb again: ")

print("In 1981, the U.S launched the first real space " +noun_1+ ". It was named the Columbia and was piloted by two brave "+plural_noun+ ". They had practiced "+verbing+" for two years and were expert "+plural_noun+". Columbia took off from "+city+" using its powerful first-stage "+plural_noun_2+" and soared off into the "+adjective1+ " blue " +noun_1 + ". At an altitude of "+num+ " feet, it went into orbit around the "+ noun2+". For people watching from earth, it was a/an "+adjective2+" sight to "+verb+"! Who could really "+verb+" that there were two "+plural_noun_2+" in space? It was mind "+verbing2+". After "+num+" Orbits, the shuttle landed "+adverb+" at an air force "+noun3+". It was a/n "+adjective3+" day fpr the U.S. Space Program. ")